var zones = ['An urban area','A suburban area','A town','A village','A rural area'];

var countries = [

    // <15
    // 15% for 1 = 15%
    {
        'United States':[
            'Washington State',
            'Oregon',
            'California',
            'Nevada',
            'Idaho',
            'Utah',
            'Arizona',
            'New Mexico',
            'Colorado',
            'Wyoming',
            'Montana',
            'North Dakota',
            'South Dakota',
            'Nebraska',
            'Kansas',
            'Oklahoma',
            'Texas',
            'Louisiana',
            'Arkansas',
            'Missouri',
            'Iowa',
            'Minnesota',
            'Wisconsin',
            'Michigan',
            'Ohio',
            'Indiana',
            'Illinois',
            'Kentucky',
            'Tennessee',
            'Mississippi',
            'Alabama',
            'Florida',
            'Georgia',
            'South Carolina',
            'North Carolina',
            'Virginia',
            'West Virginia',
            'Washington, DC',
            'Maryland',
            'Delaware',
            'Pennsylvania',
            'New Jersey',
            'New York',
            'Connecticut',
            'Rhode Island',
            'Massachusetts',
            'Vermont',
            'New Hampshire',
            'Maine',
            'Alaska',
            'Hawaii',
        ]
    },

    // 15 - <45
    // 30% for 8 = 3.75%
    {
        'Canada':[
            'Yukon',
            'Northwest Territories',
            'Nunavut',
            'British Columbia',
            'Alberta',
            'Saskatchewan',
            'Manitoba',
            'Ontario',
            'Quebec',
            'New Brunswick',
            'Prince Edward Island',
            'Nova Scotia',
            'Newfoundland and Labrador'
        ],
        'Mexico':[
            'Baja California',
            'Baja California Sur',
            'Sonora',
            'Chihuahua',
            'Coahuila',
            'Nuevo León',
            'Tamaulipas',
            'Sinaloa',
            'Durango',
            'Zacatecas',
            'San Luis Potosí',
            'Nayarit',
            'Aguascalientes',
            'Jalisco',
            'Guanajuato',
            'Querétaro',
            'Hidalgo',
            'Tlaxcalo',
            'Veracruz',
            'Colima',
            'Michoacán',
            'State of México',
            'México City',
            'Morelos',
            'Puebla',
            'Guerrero',
            'Oaxaca',
            'Tabasco',
            'Chiapas',
            'Campeche',
            'Yucatán',
            'Quintana Roo'
        ],
        'Brazil':[
            'Roraima',
            'Amazonas',
            'Acre',
            'Amapá',
            'Pará',
            'Rodônia',
            'Tocantins',
            'Maranhão',
            'Piaui',
            'Ceará',
            'Rio Grande do Norte',
            'Paraíba',
            'Pernambuco',
            'Alagoas',
            'Sergipe',
            'Bahia',
            'Mato Grosso',
            'Goiás',
            'Federal District',
            'Mato Grosso do Sul',
            'Minas Gerais',
            'Espírito Santo',
            'São Paulo',
            'Rio de Janeiro',
            'Paraná',
            'Santa Catarina',
            'Rio Grande do Sul'
        ],
        'United Kingdom':[
            'Isle of Man',
            'Jersey',
            'Northern Ireland',
            'Scotland',
            'Wales',
            'North West England',
            'North East England',
            'Yorkshire and the Humber',
            'West Midlands',
            'East Midlands',
            'South West England',
            'South East England',
            'Greater London',
            'East of England'
        ],
        'France':[
            'Hauts-de-France',
            'Normandy',
            'Île-de-France',
            'Grand Est',
            'Brittany',
            'Pays de la Loire',
            'Centre-Val de Loire',
            'Burgogne-Franche-Comté',
            'Nouvelle-Aquitaine',
            'Auvergne-Rhône-Alpes',
            'Occitania',
            'Provence-Alpes-Côtes d\'Azur',
            'Corsica',
        ],

        'Russia':[
            'Kaliningrad Oblast',
            'Pskov Oblast',
            'Novgorod Oblast',
            'Leningrad Oblast',
            'Saint Petersburg',
            'Karelia',
            'Murmansk Oblast',
            'Vologda Oblast',
            'Arkhangelsk Oblast',
            'Komi',
            'Nenets Autonomous Okrug',
            'Tver Oblast',
            'Yaroslavl Oblast',
            'Kostroma Oblast',
            'Smolensk Oblast',
            'Moscow',
            'Moscow Oblast',
            'Vladimir Oblast',
            'Ivanovo Oblast',
            'Bryansk Oblast',
            'Kaluga Oblast',
            'Kursk Oblast',
            'Oryol Oblast',
            'Tula Oblast',
            'Lipetsk Oblast',
            'Ryazan Oblast',
            'Belgorod Oblast',
            'Voronezh Oblast',
            'Tambov Oblast',
            'Volgograd Oblast',
            'Rostov Oblast',
            'Kalmykia',
            'Astrakhan Oblast',
            'Krasnodar Krai',
            'Adygea',
            'Stavropol Krai',
            'Karachay-Cherkess Republic',
            'Kabadino-Balkarian Republic',
            'Ingushetia',
            'Chechnya',
            'Dagestan',
            'North Ossetia-Alania',
            'Nizhny Novgorod Oblast',
            'Kirov Oblast',
            'Perm Krai',
            'Mordovia',
            'Chuvashia',
            'Mari El',
            'Penza Oblast',
            'Ulyanovsk Oblast',
            'Tatarstan',
            'Udmurtia',
            'Saratov Oblast',
            'Samara Oblast',
            'Orenburg Oblast',
            'Bashkortostan',
            'Sverdlosk Oblast',
            'Khanty-Mansi Autonomous Okrug',
            'Yamalo-Nenets Autonomous Okrug',
            'Chelyabinsk Oblast',
            'Kurgan Oblast',
            'Tyumen Oblast',
            'Omsk Oblast',
            'Tomsk Oblast',
            'Krasnoyarsk Krai',
            'Irkutsk Oblast',
            'Novosibirsk Oblast',
            'Kemerovo Oblast',
            'Khakassia',
            'Altai Krai',
            'Altai Republic',
            'Tuva Republic',
            'Sakha Republic',
            'Chukotka Autonomous Okrug',
            'Magadan Oblast',
            'Kamchatka Krai',
            'Khabarovsk Krai',
            'Sakhalin Oblast',
            'Buryatia',
            'Zabaykalsky Krai',
            'Amur Oblast',
            'Jewish Autonomous Oblast',
            'Primorsky Krai'
        ],
        'Japan':[
            'Hokkaidō',
            'Aomori Prefecture',
            'Iwate Prefecture',
            'Miyagi Prefecture',
            'Akita Prefecture',
            'Yamagata Prefecture',
            'Fukushima Prefecture',
            'Ibaraki Prefecture',
            'Tochigi Prefecture',
            'Gunma Prefecture',
            'Saitama Prefecture',
            'Chiba Prefecture',
            'Tōkyō',
            'Kanagawa Prefecture',
            'Niigata Prefecture',
            'Toyama Prefecture',
            'Ishikawa Prefecture',
            'Fukui Prefecture',
            'Yamanashi Prefecture',
            'Nagano Prefecture',
            'Gifu Prefecture',
            'Shizuoka Prefecture',
            'Aichi Prefecture',
            'Mie Prefecture',
            'Shiga Prefecture',
            'Kyōto Prefecture',
            'Ōsaka Prefecture',
            'Hyōgo Prefecture',
            'Nara Prefecture',
            'Wakayama Prefecture',
            'Tottori Prefecture',
            'Shimane Prefecture',
            'Okayama Prefecture',
            'Hiroshima Prefecture',
            'Yamaguchi Prefecture',
            'Tokushima Prefecture',
            'Kagawa Prefecture',
            'Ehime Prefecture',
            'Kōchi Prefecture',
            'Fukuoka Prefecture',
            'Saga Prefecture',
            'Nagasaki Prefecture',
            'Kumamoto Prefecture',
            'Ōita Prefecture',
            'Miyazaki Prefecture',
            'Kagoshima Prefecture',
            'Okinawa Prefecture'
        ],
        'Australia':[
            'Western Australia',
            'Northern Territory',
            'Queensland',
            'South Australia',
            'New South Wales',
            'Victoria',
            'Tasmania',
            'Australian Capital Territory',
            'Christmas Island',
            'Cocos (Keeling) Island',
        ],
    },

    // 45 - <75
    // 30% for 16 = 1.875%
    {
        'Argentina':[
            'Jujuy',
            'Salta',
            'Chaco',
            'Formosa',
            'San Juan',
            'La Rioja',
            'Catamarca',
            'Tucumán',
            'Santiago del Estero',
            'Mendoza',
            'San Luis',
            'Córdoba',
            'Santa Fe',
            'Corrientes',
            'Misiones',
            'Neuquén',
            'Río Negro',
            'La Pampa',
            'Buenos Aires Province',
            'City of Buenos Aires',
            'Entre Ríos',
            'Chubut',
            'Santa Cruz',
            'Tierra del Fuego'
        ],
        'Norway':[
            'Troms og Finnmark',
            'Nordland',
            'Trøndelag',
            'Møre og Romsdal',
            'Vestland',
            'Rogaland',
            'Agder',
            'Vestfold og Telemark',
            'Oslo',
            'Innlandet'
        ],
        'Sweden':[
            'Norbotten County',
            'Västerbotten County',
            'Jämtland County',
            'Västernorrland County',
            'Dalarna County',
            'Gävleborg County',
            'Värmland County',
            'Örebro County',
            'Västmanland County',
            'Södermanland County',
            'Uppsala County',
            'Stockholm County',
            'Västra Götaland County',
            'Jönköping County',
            'Östergötland County',
            'Halland County',
            'Kronoberg County',
            'Kalmar County',
            'Gotland County',
            'Skåne County',
            'Blekinge County'
        ],
        'Netherlands':[
            'Friesland',
            'Groningen',
            'North Holland',
            'Flevoland',
            'Overijssel',
            'Drenthe',
            'South Holland',
            'Utrecht',
            'Gelderland',
            'Zeeland',
            'North Brabant',
            'Limburg'
        ],
        'Germany':[
            'Bremen',
            'Hamburg',
            'Lower Saxony',
            'Berlin',
            'North Rhine-Westphalia',
            'Rhineland-Westphalia',
            'Saxony',
            'Hesse',
            'Baden-Württemberg',
            'Bavaria'
            // Bundeslander with cities with street view
        ],

        'Austria':[
            'Upper Austria',
            'Lower Austria',
            'Vienna',
            'Vorarlberg',
            'Tyrol',
            'Salzburg',
            'Styria',
            'Burgenland',
            'Carinthia'
        ],
        'Poland':[
            'West Pomeranian Voivodeship',
            'Pomeranian Voivodeship',
            'Warmian-Masurian Voivodeship',
            'Lubusz Voivodeship',
            'Greater Poland Voivodeship',
            'Kuyavian-Pomeranian Voivodeship',
            'Masovian Voivodeship',
            'Podlaskie Voivodeship',
            'Lower Silesian Voivodeship',
            'Łódź Voivodeship',
            'Opole Voivodeship',
            'Silesian Voivodeship',
            'Świętokrzyskie Voivodeship',
            'Lublin Voivodeship',
            'Lesser Poland Voivodeship',
            'Subcarpathian Voivodeship'
        ],
        'Spain':[
            'Galicia',
            'Asturias',
            'Cantabria',
            'Basque Country',
            'La Rioja',
            'Navarre',
            'Castile and León',
            'Aragon',
            'Catalonia',
            'Extremadura',
            'Community of Madrid',
            'Castilla-La Mancha',
            'Valencian Community',
            'Balearic Islands',
            'Andalusia',
            'Murcia',
            'Canary Islands',
            'Ceuta',
            'Melilla'
        ],
        'Italy':[
            'Valle d\'Aosta',
            'Piedmont',
            'Lombardy',
            'Trentino Alto Adige / Südtirol',
            'Veneto',
            'Friuli-Venezia Giulia',
            'Liguria',
            'Emilia-Romagna',
            'Tuscany',
            'Umbria',
            'Marche',
            'Lazio',
            'Abruzzo',
            'Molise',
            'Campania',
            'Basilicata',
            'Puglia',
            'Calabria',
            'Sicily',
            'Sardinia'
        ],
        'Romania':[
            'Satu Mare County',
            'Maramureş County',
            'Bistrița-Năsăud County',
            'Suceava County',
            'Botoșani County',
            'Bihor County',
            'Sălaj County',
            'Cluj County',
            'Mureș County',
            'Harghita County',
            'Neamț County',
            'Bacău County',
            'Iași County',
            'Vaslui County',
            'Arad County',
            'Timiș County',
            'Hunedoara County',
            'Alba County',
            'Sibiu County',
            'Brașov County',
            'Covasna County',
            'Vrancea County',
            'Galați County',
            'Caraș-Severin County',
            'Mehedinți County',
            'Gorj County',
            'Vâlcea County',
            'Argeș County',
            'Dâmbovița County',
            'Prahova County',
            'Buzău County',
            'Brăila County',
            'Tulcea County',
            'Dolj County',
            'Olt County',
            'Teleorman County',
            'Giurgiu County',
            'Ilfov County',
            'București County',
            'Ialomița County',
            'Călărași County',
            'Constanța County'
        ],
        'Turkey':[
            'Marmara Region',
            'Black Sea Region',
            'Aegean Region',
            'Central Anatolia Region',
            'Eastern Anatolia Region',
            'Mediterranean Region',
            'Southeastern Anatolia Region'
        ],
        'South Africa':[
            'Limpopo',
            'North West',
            'Gauteng',
            'Mpumalanga',
            'Northern Cape',
            'Free State',
            'KwaZulu-Natal',
            'Western Cape',
            'Eastern Cape'
        ],
        'India':[
            'Punjab',
            'Chandigarh',
            'Uttarkhand',
            'Rajasthan',
            'Haryana',
            'Delhi',
            'Uttar Pradesh',
            'Gujarat',
            'Maharashtra',
            'Telangana',
            'Karnataka',
            'Andhra Pradesh',
            'Tamil Nadu'
            //No coverage in other states
        ],
        'Thailand':[
            'Northern Thailand',
            'Northeastern Thailand',
            'Central Thailand',
            'Southern Thailand'
        ],
        'Indonesia':[
            'Sumatra',
            'Java',
            'Kalimantan',
            'Lesser Sunda Islands',
            'Sulawesi'
            //'Maluku Islands',
            //'Western New Guinea'
        ],
        'New Zealand':[
            'North Island',
            'South Island'
        ],
    },

    // 75 - <90
    // 15% for 29 = 0.517%
    {
        'Guatemala': null,
        'Colombia': null/*[
            'Cordillera Oriental (Eastern Ranges)',
            'Cordillera Occidental/Central (Western/Central Ranges)',
            'Caribbean Region',
            'Pacific/Chocó Region',
            'Orinoquía Region',
            'Amazonía Region',
            'Insular Region'
        ]*/,
        'Peru': null/*[
            'La Costa (Coast)',
            'La Sierra (Highladns)',
            'La Selva (Rainforest)'
        ]*/,
        'Chile':[
            'Arica y Parinacota Region',
            'Tarapacá Region',
            'Antofagasta Region',
            'Atacama Region',
            'Coquimbo Region',
            'Valparaíso Region (Mainland)',
            'Easter Island',
            'Santiago Metropolitan Region',
            'O\'Higgins Region',
            'Maule Region',
            'Ñuble Region',
            'Biobío Region',
            'Auracanía Region',
            'Los Ríos Region',
            'Los Lagos Region',
            'Aysén Region',
            'Magallanes Region',
        ],
        'Finland':[
            'Lapland',
            'North Ostrobothnia',
            'Kainuu',
            'Ostrobothnia',
            'South Ostrobothnia',
            'Central Ostrobothnia',
            'Central Finland',
            'North Savo',
            'North Karelia',
            'Satakunta',
            'Pirkanmaa',
            'Kanta-Häme',
            'Päijät-Häme',
            'South Savo',
            'South Karelia',
            'Åland',
            'Southwest Finland',
            'Uusimaa',
            'Kymenlaakso'
        ],
        'Denmark':[
            'Nordjylland',
            'Midtjylland',
            'Syddanmark',
            'Sjælland',
            'Hovedstaden'
        ],
        'Estonia': null,
        'Latvia': null,
        'Lithuania': null,
        'Ireland':[
            'County Donegal',
            'County Mayo',
            'County Sligo',
            'County Leitrim',
            'County Cavan',
            'County Monaghan',
            'County Louth',
            'County Roscommon',
            'County Longford',
            'County Westmeath',
            'County Meath',
            'County Dublin',
            'County Galway',
            'County Offaly',
            'County Laois',
            'County Kildare',
            'County Wicklow',
            'County Clare',
            'County Limerick',
            'County Tipperary',
            'County Kilkenny',
            'County Carlow',
            'County Wexford',
            'County Kerry',
            'County Cork',
            'County Waterford'
        ],
        'Belgium':[
            'Flanders',
            'Wallonia',
            'Brussels'
        ],
        'Portugal':[
            'Norte',
            'Centro',
            'Lisboa',
            'Alentejo',
            'Algarve',
            'Azores',
            'Madeira'
        ],
        'Switzerland': null/*[
            'Lake Geneva Region',
            'Espace Mittelland',
            'Northwestern Switzerland',
            'Zurich',
            'Eastern Switzerland',
            'Central Switzerland',
            'Ticino'
        ]*/,
        'Czechia': null/*[
            'Bohemia',
            'Moravia',
            'Silesia'
        ]*/,
        'Slovakia': null/*[
            'Bratislava Region',
            'Western Slovakia',
            'Central Slovakia',
            'Eastern Slovakia'
        ]*/,
        'Hungary':[
            'Győr-Moson-Sopron',
            'Komárom-Esztergom',
            'Nógrád',
            'Heves',
            'Borsod-Abaúj-Zemplén',
            'Szabolcs-Szatmár-Bereg',
            'Vas',
            'Veszprém',
            'Fejér',
            'Pest',
            'Budapest',
            'Jász-Nagykun-Szolnok',
            'Hajdú-Bihar',
            'Zala',
            'Somogy',
            'Baranya',
            'Tolna',
            'Bács-Kiskun',
            'Csongrád-Csanád',
            'Békés'
        ],
        'Croatia':[
            'Istria',
            'Croatia Proper',
            'Slavonia',
            'Dalmatia'
        ],
        'Bulgaria':[
            'Vidin Oblast',
            'Montana Oblast',
            'Vratsa Oblast',
            'Pleven Oblast',
            'Ruse Oblast',
            'Razgrad Oblast',
            'Silistra Oblast',
            'Dobrich Oblast',
            'Lovech Oblast',
            'Gabrovo Oblast',
            'Veliko Tarnovo Oblast',
            'Targovishte Oblast',
            'Shumen Oblast',
            'Varna Oblast',
            'Kyustendil Oblast',
            'Pernik Oblast',
            'Sofia City Oblast',
            'Sofia Oblast',
            'Plovdiv Oblast',
            'Stara Zagora Oblast',
            'Sliven Oblast',
            'Yambol Oblast',
            'Burgas Oblast',
            'Blagoevgrad Oblast',
            'Pazardzhik Oblast',
            'Smolyan Oblast',
            'Kardzhali Oblast',
            'Haskovo Oblast',
        ],
        'Greece':[
            'East Macedonia and Thrace',
            'Central Macedonia',
            //'Mount Athos',
            'Western Macedonia',
            'Epirus',
            'Thessaly',
            'Ionian Islands',
            'Western Greece',
            'Central Greece',
            'North Aegean',
            'Peloponnese',
            'Attica',
            'Southern Aegean',
            'Crete'
        ],
        'Ukraine':[
            'Volyn Oblast',
            'Lviv Oblast',
            'Zakarpattia Oblast',
            'Ivano-Frankivsk Oblast',
            'Chernivtsi Oblast',
            'Ternopil Oblast',
            'Khmel Oblast',
            'Rivne Oblast',
            'Zhytomyr Oblast',
            'Vinnytsia Oblast',
            'Odesa Oblast',
            'Mylokaiv Oblast',
            'Kirovohrad Oblast',
            'Cherkasy Oblast',
            'Kyiv Oblast',
            'Kyiv',
            'Chernihiv Oblast',
            'Sumy Oblast',
            'Poltava Oblast',
            'Kharkiv Oblast',
            'Dnipropetrovsk Oblast',
            'Donetsk Oblast',
            'Zaporizhzhia Oblast'
            //'Kherson Oblast',
            //'Luhansk Oblast',
            //'Crimea',
            //'Sevastopol'
        ],
        'Israel':[
            'Northern District',
            'Haifa District',
            'Central District',
            'Tel Aviv District',
            'Jerusalem District',
            'Southern District',
        ],
        'Ghana': null,
        'Botswana': null,
        'Sri Lanka':[
            'Northern Province',
            'North Western Province',
            'North Central Province',
            'Central Province',
            'Eastern Province',
            'Western Province',
            'Sabaragamuwa Province',
            'Uva Province',
            'Southern Province'
        ],
        'Cambodia': null,
        'Philippines':[
            'Luzon',
            'Visayas',
            'Mindanao'
        ],
        'Malaysia':[
            'Peninsular Malaysia',
            'Malaysian Borneo'
        ],
        'Singapore': null,
        'Taiwan': null/*[
            'Outlying Islands',
            'North Taiwan',
            'West Taiwan',
            'South Taiwan',
            'East Taiwan'
        ]*/,
    },

    // 90 - <98
    // 8% for 27 = 0.296%
    {
        'Dominican Republic':[
            'Santo Domingo',
            'Santiago de los Caballeros'
        ],
        'Puerto Rico': null,
        'Ecuador':[
            'Galápagos',
            'Esmeraldas',
            'Imbabura',
            'Carchi',
            'Sucumbíos',
            'Manabí',
            'Santo Domingo de los Tsáchilas',
            'Pichincha',
            'Napo',
            'Orellana',
            'Los Ríos',
            'Cotopaxi',
            'Bolívar',
            'Tungurahua',
            'Pastaza',
            'Santa Elena',
            'Guayas',
            'Chimborazo',
            'Cañar',
            'Azuay',
            'Morona Santiago',
            'El Oro',
            'Loja'
            //'Zamora Chinchipe'
        ],
        'Bolivia': null,
        'Uruguay': null,
        'Iceland': null,
        'Luxembourg': null,
        'Slovenia': null,
        'Serbia': null/*[
            'Vojvodina',
            'Belgrade',
            'Southern Serbia'
        ]*/,
        'Montenegro': null,
        'Albania': null,
        'North Macedonia': null,
        'Palestine': null,
        'Jordan': null,
        'United Arab Emirates': null/*[
            'Abu Dhabi Emirate', // Sir Baniyas
            'Dubai Emirate',
            'Sharjah Emirate',
            'Ajman Emirate',
            'Umm al-Quwain Emirate',
            'Ras al-Khaimah Emirate',
            'Fujairah Emirate'
        ]*/,
        'Tunisia': null/*[
            'Bizerte Governorate',
            'Ariana Governorate',
            'Tunis Governorate',
            'Ben Arous Governorate',
            'Nabeul Governorate',
            'Sousse Governorate',
            'Kairouan Governorate',
            'Monastir Governorate',
            'Mahdia Governorate',
            'Sfax Governorate',
            'Gabès Governorate',
            'Mendenine Governorate',
            // no street view in other 12 governorates
        ]*/,
        'Senegal': null,
        'Nigeria': null,
        'Uganda': null,
        'Kenya': null,
        'Lesotho': null,
        'Eswatini': null/*[
            'Hhohho Region',
            'Manzini Region',
            'Lubombo Region',
            'Shiselweni Region'
        ]*/,
        'Kyrgyzstan': null,
        'Mongolia': null,
        'Bangladesh': null/*[
            'Rangpur Division',
            'Rajshahi Division',
            'Mymensingh Division',
            'Sylhet Division',
            'Dhaka Division',
            'Khulna Division',
            'Barisal Divison',
            'Chittagong Division'
        ]*/,
        'Bhutan': null,
        'South Korea':[
            'Gangwon-do',
            'Gyeonggi-do',
            'Seoul',
            'Incheon',
            //'Chungcheongbuk-do',
            'Chungcheongnam-do',
            //'Sejong',
            'Daejeon',
            'Gyeongsangbuk-do',
            'Gyeongsangnam-do',
            'Daegu',
            //'Ulsan',
            'Busan',
            'Jeollabuk-do',
            'Jeollanam-do',
            'Gwangju',
            'Jeju-do'
        ]
    },

    // 98 - <100
    // 2% for 17 = 0.118%
    {
        'US Virgin Islands':[
            'St Thomas',
            'St John',
            'St Croix'
        ],
        'Curac̨ao': null,
        'Greenland': null,
        'Faroe Islands':[
            'Norðoyggjar',
            'Eysturoy',
            'Streymoy',
            'Vágar',
            'Sandoy',
            'Suðuroy'
        ],
        'Jersey': null,
        'Isle of Man': null,
        'Monaco': null,
        'Andorra':[
            'La Massana',
            'Ordino',
            'Canillo',
            'Encamp',
            'Andorra La Vella',
            'Escaldes-Engordany',
            'San Julià de Lòria'
        ],
        'Malta':[
            'Gozo and Comino',
            'Mainland Malta (Northeast)',
            'Mainland Malta (Southwest)'
        ],
        'San Marino': null,
        'Réunion':[
            'Saint Denis',
            'Saint Benoît',
            'Saint Denis',
            'Saint Pierre'
        ],
        'Guam': null,
        'Northern Mariana Islands': null,
        'Midway Atoll': null,
        'American Samoa': null,
        'Hong Kong': null,
        'Laos': null
    }

]

function randomItem(itemArray) {
    return itemArray[Math.floor(Math.random() * itemArray.length)];
}

function generate(e) {

    if (e?.target.tagName == 'INPUT') return;
    
    let places = document.getElementById('places');
    places.replaceChildren();

    for(let i = 0; i < document.querySelector('input').value; i++) {
        let listItem = document.createElement('li');
        listItem = choosePlace(listItem);
        places.appendChild(listItem);
    }
}

function choosePlace(listItem) {
    listItem.innerText = randomItem(zones) + " in ";
    
    let rand = Math.floor(Math.random() * 100);
    let grouping;
    switch(true) {
        case(rand < 15): grouping = 0; break;
        case(rand < 45): grouping = 1; break;
        case(rand < 75): grouping = 2; break;
        case(rand < 90): grouping = 3; break;
        case(rand < 98): grouping = 4; break;
        default: grouping = 5;
    }

    let country = randomItem(Object.keys(countries[grouping]));
    
    let regions = countries[grouping][country];
    if(regions) listItem.innerText += randomItem(regions) + ", ";

    listItem.innerText += country;
    return listItem;
}

document.onload = generate();